import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App 32424",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}  `}>
        <div className="bg-[#FFFBF2]">
          <div className="container ]">
            <Header />
          </div>
          <div className="flex flex-col min-h-[100vh]">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
